#!/bin/bash
#
# My Proxmox VE 9.0+/Proxmox Backup Server 4.0+ setup script
#
# Copyright (C) 2022-2026 Alan Doyle
#
# https://github.com/alandoyle/proxmox-setup/
#
# License: MIT
# Based originally in part on some scripts from https://github.com/tteck/Proxmox/ and https://github.com/MacRimi/ProxMenux
#
################################################################################################################################################################
VERSION_ID="1"
. /etc/os-release
################################################################################################################################################################
get_proxmox_version()
{
    if [ -f /usr/bin/pveversion ] ; then
        PROXMOX_VERSION="Proxmox VE `/usr/bin/pveversion|cut -d/ -f2`"
        PROXMOX_TYPE=pve
        STARSHIP_COLOR1=#3B4252
        STARSHIP_COLOR2=#4C566A
        STARSHIP_COLOR3=#86BBD8
    elif [ -f /usr/sbin/proxmox-backup-manager ] ; then
        PROXMOX_VERSION="Proxmox Backup Server `/usr/sbin/proxmox-backup-manager versions | cut -d ' ' -f5`"
        PROXMOX_TYPE=pbs
        STARSHIP_COLOR1=#3B5242
        STARSHIP_COLOR2=#4C6A56
        STARSHIP_COLOR3=#86D9BA
    else
        PROXMOX_VERSION="UNKNOWN!!!!"
        PROXMOX_TYPE=unknown
    fi
}
#
################################################################################################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi
#
################################################################################################################################################################
#
# Check it's actually a Proxmox server
#
if [ ! -f /etc/grub.d/000_proxmox_boot_header ] ; then
    echo "ERROR: This script needs to be run on a Proxmox Server only."
    exit 98
fi
#
################################################################################################################################################################
#
# Check versions
#
if [ "${ID}" != "debian" -o ${VERSION_ID} -lt 13 ] ; then
    echo "ERROR: This script needs to be run on Proxmox VE 9.x (or higher) or Proxmox Backup Server 4.x (or higher)"
    exit 97
fi
#
################################################################################################################################################################
#
# Check if already run
#
if [ -f /etc/pve/.setup ] ; then
    echo "ERROR: This script has already been run."
    exit 96
fi
#
################################################################################################################################################################
#
# Create default config file if one doesn't exist
#
if [ ! -f /etc/default/proxmox-setup ] ; then
    cat <<EOF >/etc/default/proxmox-setup
#
# Set PROXMOX_ENV to LIVE if you have a subscription, otherwise the "No Subscriptions" repos will be enabled.
#
PROXMOX_ENV=DEV
EOF
fi
#
################################################################################################################################################################
#
# Include OS details
#
[ -f /etc/default/proxmox-setup ] && . /etc/default/proxmox-setup
get_proxmox_version
echo "Setting up ${PROXMOX_VERSION} [${PROXMOX_ENV}]"
#
################################################################################################################################################################
#
# Setup repositories
#
if [ "${PROXMOX_ENV}" != "LIVE" ] ; then
    echo "Configuring TRIXIE repositories"
    [ ! -d /etc/apt/sources.list.d.SAVED ] && mkdir -p /etc/apt/sources.list.d.SAVED
    #
    ################################################################################################################################################################
    #
    echo "Disabling Enterprise Repositories"
    if [ -f /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources -a ! -f /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources.SAVED ] ; then
        cp /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources /etc/apt/sources.list.d.SAVED
        grep "Enabled: false" /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources >/dev/null
        if [ $? -ne 0 ] ; then
            cat /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources | grep -v Enabled > /tmp/${PROXMOX_TYPE}-enterprise.sources
            echo "Enabled: false" >> /tmp/${PROXMOX_TYPE}-enterprise.sources
            mv /tmp/${PROXMOX_TYPE}-enterprise.sources /etc/apt/sources.list.d/${PROXMOX_TYPE}-enterprise.sources
        fi
    fi
    #
    ################################################################################################################################################################
    #
    if [ ! -f /etc/apt/sources.list.d/proxmox.sources ] ; then
    echo "Creating 'no-subscription' APT source"
    cat <<EOF >/etc/apt/sources.list.d/proxmox.sources
Types: deb
URIs: http://download.proxmox.com/debian/pve
Suites: trixie
Components: pve-no-subscription
Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
EOF
    fi
    #
    ################################################################################################################################################################
    #
    if [ -f /etc/apt/sources.list.d/ceph.list -a ! -f /etc/apt/sources.list.d/ceph.list.SAVED ] ; then
        echo "Updating ceph.sources"
        cp /etc/apt/sources.list.d/ceph.sources /etc/apt/sources.list.d.SAVED
        grep "Enabled: false" /etc/apt/sources.list.d/ceph.sources >/dev/null
        if [ $? -ne 0 ] ; then
            cat /etc/apt/sources.list.d/ceph.sources | grep -v Enabled > /tmp/ceph.sources
            echo -e "Enabled: false\n" >> /tmp/ceph.sources
            echo "Types: deb" >> /tmp/ceph.sources
            echo "URIs: http://download.proxmox.com/debian/ceph-squid" >> /tmp/ceph.sources
            echo "Suites: trixie" >> /tmp/ceph.sources
            echo "Components: no-subscription" >> /tmp/ceph.sources
            echo "Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg" >> /tmp/ceph.sources
            mv /tmp/ceph.sources /etc/apt/sources.list.d/ceph.sources
        fi
    fi
fi
#
################################################################################################################################################################
#
echo "Upgrade Proxmox (please be patient)"
apt-get update >/dev/null
apt-get -y dist-upgrade >/dev/null
#
################################################################################################################################################################
#
if [ -f /etc/apt/apt.conf.d/no-nag-script ] ; then
    rm /etc/apt/apt.conf.d/no-nag-script
fi
if [ ! -f /etc/apt/apt.conf.d/99nonagscript ] ; then
    echo "Disable Subscription Nag"
    echo "DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/data.status/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };" >/etc/apt/apt.conf.d/99nonagscript

    apt-get --reinstall install proxmox-widget-toolkit >/dev/null
fi
#
################################################################################################################################################################
#
echo "Adding additional applications"
GRUBEFI=
if [ -f /boot/efi/EFI/proxmox/grubx64.efi ] ; then
    GRUBEFI=grub-efi-amd64
fi

CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | uniq | awk -F: '{ print $2 }' | tr -d "[:blank:]"`
CPU_MICROCODE=
case $CPU_VENDOR in
    GenuineIntel)  CPU_MICROCODE=intel-microcode ;;
    AuthenticAMD)  CPU_MICROCODE=amd64-microcode ;;
esac

apt-get -y install sudo vim aptitude lsscsi git curl gnupg bash-completion logrotate p7zip p7zip-full unrar-free lm-sensors zip unzip btop iotop plocate rsync powertop command-not-found unattended-upgrades fastfetch lshw ${GRUBEFI} ${CPU_MICROCODE} >/dev/null
#
################################################################################################################################################################
#
echo "Adding non-repository applications"
if [ ! -f /usr/sbin/hddtemp ] ; then
    echo "Installing HDDTemp..."
    HDDTEMP_URL=https://ftp.debian.org/debian/pool/main/h/hddtemp/hddtemp_0.3-beta15-54_amd64.deb
    curl --fail --silent --location --output /tmp/hddtemp-linux.deb "${HDDTEMP_URL}"
    dpkg -i /tmp/hddtemp-linux.deb >/dev/null
	rm /tmp/hddtemp-linux.deb >/dev/null
fi

chmod u+s /usr/sbin/hddtemp
#
################################################################################################################################################################
#
echo "Installing STARSHIP"
STARSHIP_URL=https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
curl --fail --silent --location --output /tmp/starship.tar.gz "${STARSHIP_URL}"
tar xvf /tmp/starship.tar.gz >/dev/null 2>&1
[ -f /usr/local/bin/starship ] && rm -f /usr/local/bin/starship
mv starship /usr/bin/starship
chown root:root /usr/bin/starship
chmod a+x /usr/bin/starship
rm -f /tmp/starship.tar.gz
#
#################################################################################
#
echo "Configuring applications..."
apt-file update >/dev/null
update-command-not-found >/dev/null
if [ ! -f /etc/vim/vimrc.local -a -d /etc/vim ] ; then
    cat <<EOF >/etc/vim/vimrc.local
if filereadable("\$VIMRUNTIME/defaults.vim")
  source \$VIMRUNTIME/defaults.vim
endif
" now set the line that the defaults file is not reloaded afterwards!
let skip_defaults_vim = 1
" turn off mouse
set mouse=
" other override settings go here
syntax on
EOF
fi

[ ! -d /etc/skel/.config/btop ] && mkdir -p /etc/skel/.config/btop
if [ ! -f /etc/skel/.config/btop/btop.conf ] ; then
    echo 'color_theme = "TTY"' > /etc/skel/.config/btop/btop.conf
fi

[ ! -d /root/.config/btop ] && mkdir -p /root/.config/btop
if [ ! -f /root/.config/btop/btop.conf ] ; then
    echo 'color_theme = "TTY"' > /root/.config/btop/btop.conf
fi
#
################################################################################################################################################################
#
echo "Creating STARSHIP profiles..."
cat <<EOF >/etc/starship.toml
# Simple starship.toml file
format = """
[ ](bg:${STARSHIP_COLOR1})\\
\$username\\
\$hostname\\
\$shell\\
[](fg:${STARSHIP_COLOR1} bg:${STARSHIP_COLOR2})\\
\$directory\\
[](fg:${STARSHIP_COLOR2} bg:${STARSHIP_COLOR3})\\
\$git_branch\\
\$git_commit\\
\$git_status\\
\$git_state\\
[](fg:${STARSHIP_COLOR3})\\
\$cmd_duration\\
\$line_break\\
\$character\\
"""
command_timeout = 5000
add_newline = true

[username]
style_user = "white"
format = '[\$user](\$style bg:${STARSHIP_COLOR1})'

[hostname]
style = "bg:${STARSHIP_COLOR1}"
format = "[@\$hostname ](\$style)"

[shell]
disabled = false
bash_indicator = ">_ "
fish_indicator = "><>"
zsh_indicator = "%_ "
powershell_indicator = ">>>"
cmd_indicator = "<<<"
unknown_indicator = "?_ "
style = "bg:${STARSHIP_COLOR1}"
format = "[\$indicator](\$style)"

[directory]
truncation_length = 5
style = "bg:${STARSHIP_COLOR2}"
format = "[ \$path ](\$style)"

[git_branch]
style = "bg:${STARSHIP_COLOR3} fg:${STARSHIP_COLOR1}"
format = '[ \$symbol$branch ](\$style)'

[git_commit]
style = "bg:${STARSHIP_COLOR3} fg:${STARSHIP_COLOR1}"
format = '[ \$hash ](\$style)'

[git_status]
style = "bg:${STARSHIP_COLOR3} fg:${STARSHIP_COLOR1}"
format = '[\$all_status\$ahead_behind](\$style)'

[git_state]
style = "bg:${STARSHIP_COLOR3} fg:${STARSHIP_COLOR1}"
format = '[ \$state(\$progress_current/\$progress_total)](\$style)'

[cmd_duration]
min_time = 500
style = "fg:#eb7442"
format = " took [\$duration](\$style)"

[line_break]

[character]
success_symbol = '[-](bold green)'
# would be nice to have sudo module ehre
error_symbol = '[✕](bold red)'
vimcmd_symbol = '[N](bold blue) '
vimcmd_replace_one_symbol = '[R](bold red) '
vimcmd_replace_symbol = '[R](bold red) '
vimcmd_visual_symbol = "[V ](bold yellow)"
EOF
cat <<EOF >/etc/starship.root.toml
# Simple starship.toml file
format = """
[ ](bg:#5B0000)\\
\$username\\
\$hostname\\
\$shell\\
[](fg:#5B0000 bg:#A9191C)\\
\$directory\\
[](fg:#A9191C bg:#FF3535)\\
\$git_branch\\
\$git_commit\\
\$git_status\\
\$git_state\\
[](fg:#FF3535)\\
\$cmd_duration\\
\$line_break\\
\$character\\
"""
command_timeout = 5000
add_newline = true

[username]
style_user = "white"
format = '[\$user](\$style bg:#5B0000)'

[hostname]
style = "bg:#5B0000"
format = "[@\$hostname ](\$style)"

[shell]
disabled = false
bash_indicator = ">_ "
fish_indicator = "><>"
zsh_indicator = "%_ "
powershell_indicator = ">>>"
cmd_indicator = "<<<"
unknown_indicator = "?_ "
style = "bg:#5B0000"
format = "[\$indicator](\$style)"

[directory]
truncation_length = 5
style = "bg:#A9191C"
format = "[ \$path ](\$style)"

[git_branch]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$symbol\$branch ](\$style)'

[git_commit]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$hash ](\$style)'

[git_status]
style = "bg:#FF3535 fg:#5B0000"
format = '[\$all_status\$ahead_behind](\$style)'

[git_state]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$state(\$progress_current/\$progress_total)](\$style)'

[cmd_duration]
min_time = 500
style = "fg:#eb7442"
format = " took [\$duration](\$style)"

[line_break]

[character]
success_symbol = '[-](bold green)'
# would be nice to have sudo module here
error_symbol = '[✕](bold red)'
vimcmd_symbol = '[N](bold blue) '
vimcmd_replace_one_symbol = '[R](bold red) '
vimcmd_replace_symbol = '[R](bold red) '
vimcmd_visual_symbol = "[V ](bold yellow)"
EOF

# Update /etc/skel
[ ! -d /etc/skel/.config ] && mkdir -p /etc/skel/.config
[ -f /etc/skel/.config/starship.toml ] && rm -f /etc/skel/.config/starship.toml
ln -sf /etc/starship.toml /etc/skel/.config/starship.toml
#
################################################################################################################################################################
#
echo "Updating BASH profile..."

# Fastfetch
[ -f /etc/profile.d/neofetch.sh ] && rm /etc/profile.d/neofetch.sh
cat <<EOF >/etc/profile.d/sysinfo.sh
if [ "\${SUDO_USER}" = "" ] ; then
    clear
    fastfetch
    if [ -f /usr/bin/docker ] ; then
        echo -e "\n\tDOCKER CONTAINERS\n-------------------------------------------------------------------------------"
        docker ps --format "table {{.Names}}\t{{.State}}\t{{.Status}}\t{{.Ports}}"|sed 's/stopped/STOPPED/g'|sed 's/running/RUNNING/g'
    fi
    if [ -f /usr/sbin/pct ] ; then
        echo -e "\n\tLXC CONTAINERS\n-------------------------------------------------------------------------------"
        sudo /usr/sbin/pct list|sed 's/stopped/STOPPED/g'|sed 's/running/RUNNING/g'
    fi
    if [ -f  /usr/sbin/qm ] ; then
        echo -e "\n\tKVM MACHINES\n-------------------------------------------------------------------------------"
        sudo /usr/sbin/qm list|sed 's/stopped/STOPPED/g'|sed 's/running/RUNNING/g'
    fi
fi
EOF

# Reboot Required
[ -f /etc/profile.d/reboot-required.sh ] && rm -f /etc/profile.d/reboot-required.sh
cat <<EOF >/etc/profile.d/zzz-reboot-required.sh
if [ -f /var/run/reboot-required ] ; then
	tput setaf 1;echo [REBOOT REQUIRED]; tput setaf 7;
fi
EOF

# Terminal
cat <<EOF >/etc/profile.d/term.sh
if [ -z \${SSH_TTY} ] ; then
	export TERM=linux
fi
EOF

# Quoting Style
echo "export QUOTING_STYLE=literal" > /etc/profile.d/quoting_style.sh

# Starship
cat <<EOF >/etc/profile.d/starship.sh
tty | grep tty >/dev/null

# Only display for remote connections
if [ -f /usr/bin/starship -a \$? -ne 0 ] ; then
	[ ! -d ~/.config ] && mkdir -p ~/.config
	[ -f ~/.config/starship.toml ] && rm -f ~/.config/starship.toml
	if [ \`id -u\` -eq 0 ] ; then
		ln -sf /etc/starship.root.toml ~/.config/starship.toml
	else
		ln -sf /etc/starship.toml ~/.config/starship.toml
	fi
	eval "\$(starship init bash)"
fi
EOF

# Check if we're installing on Debian as it has a different /root/.bashrc to Ubuntu
grep "PROFILE UPDATE" /root/.bashrc >/dev/null 2>&1
if [ $? -ne 0 -a "${ID}" = "debian" ] ; then
	echo "Updating /root/.bashrc"
	echo -e "#\n# PROFILE UPDATE\nps -p 2 >/dev/null # LXD Container check\nif [ \$? -ne 0 -o \"\${SUDO_USER}\" != \"\" ] ; then\n\t. /root/.bash_aliases\nfi" >> /root/.bashrc
fi

# Proxmox VE specific aliases
if [ "${PROXMOX_TYPE}" = "pve" ] ; then
    cat <<EOF >/etc/profile.d/proxmox.sh
alias lsct='sudo /usr/sbin/pct list'
alias ctup='sudo /usr/sbin/pct start'
alias ctdn='sudo /usr/sbin/pct stop'

alias lsvm='sudo /usr/sbin/qm list'
alias vmup='sudo /usr/sbin/qm start'
alias vmdn='sudo /usr/sbin/qm stop'
EOF
fi

# Add Storage path (if available)
if [ "${PROXMOX_TYPE}" = "pve" ] ; then
    cat <<EOF >/etc/profile.d/storage-path.sh
if [ -d /Storage/bin ] ; then
    export PATH=\$PATH:/Storage/bin
fi
EOF
fi
#
################################################################################################################################################################
#
if [ -d /usr/lib/firmware.prev ] ; then
    echo "Update firmware"
    [ -d /usr/lib/firmware ] && rm -rf /usr/lib/firmware >/dev/null
    mv /usr/lib/firmware.prev /usr/lib/firmware >/dev/null
    apt-get -y --reinstall install pve-firmware ${CPU_MICROCODE} >/dev/null
fi
#
################################################################################################################################################################
#
if [ ! -f /etc/default/grub.d/iommu.cfg ] ; then
    echo "Enable IOMMU"
    IOMMU_CPU="amd_iommu=on"
    dmidecode -s processor-manufacturer | grep Intel >/dev/null
    [ $? -eq 0 ] && IOMMU_CPU="intel_iommu=on"
    cat <<EOF >/etc/default/grub.d/iommu.cfg
# Enable IOMMU
GRUB_CMDLINE_LINUX_DEFAULT="${IOMMU_CPU} iommu=pt \${GRUB_CMDLINE_LINUX_DEFAULT}"
#
# NOTE: Only enable the following line IF there are problems with PCI passthru
# GRUB_CMDLINE_LINUX_DEFAULT="pcie_acs_override=downstream,multifunction \${GRUB_CMDLINE_LINUX_DEFAULT}"
EOF
    cat <<EOF >>/etc/modules
vfio
vfio_iommu_type1
vfio_pci
vfio_virqfd
EOF
    update-initramfs -u -k all >/dev/null
    update-grub2 >/dev/null
fi
if [ ! -f /usr/local/bin/lsiommu ] ; then
    cat <<EOF >>/usr/local/bin/lsiommu
#!/bin/bash
for d in \$(find /sys/kernel/iommu_groups/ -type l | sort -n -k5 -t/); do
    n=\${d#*/iommu_groups/*}; n=\${n%%/*}
    printf '[Group %s] ' "\$n"
    lspci -nns "\${d##*/}"
done;
EOF
    chmod a+x /usr/local/bin/lsiommu
fi
#
################################################################################################################################################################
#
echo "[ -f /etc/bash.aliases ] && . /etc/bash.aliases" > /etc/profile.d/aliases.sh
cat <<EOF >/etc/bash.aliases

alias dfspace='df -hT -x cgmfs -x snap -x devtmpfs -x fuse -x overlay -x efivarfs | egrep -v "shm|run/|/tmp"'
alias pg='less'
alias cls='clear'
alias btop='btop --utf-force'
alias goroot='sudo -s'
alias go64='sudo -s'

# Change directory aliases
alias home='cd ~'
alias cd..='cd ..'

# cd into the old directory
alias bd='cd "\$OLDPWD"'

# Remove a directory and all files
alias rmd='/bin/rm  --recursive --force --verbose '

# Alias's for multiple directory listing commands
alias ls='ls --color=auto'
alias la='ls -lAh' # show hidden files
alias lf='ls -aFh' # file type extensions
alias lx='ls -l --sort=extension' # sort by extension
alias lk='ls -lSr' # sort by size
alias lm='ls -lr --sort=time --time=mtime' # sort by modified time
alias lu='ls -lr --sort=time --time=atime' # sort by access time
alias lr='ls -lR' # recursive ls
alias lt='ls -ltr' # sort by date
alias lw='ls -aC' # wide listing format
alias ll='ls -alF --group-directories-first' # long listing format
alias labc='ls -l --sort=name' #alphabetical sort
alias lff="ls -l | egrep -v '^d'" # files only
alias ldir="ls -l | egrep '^d'" # directories only

# Search command line history
alias h='history | grep '

# Hardware info
alias meminfo='sudo lshw -short -C memory'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# Extracts any archive(s) (if unp isn't installed)
extract () {
	for archive in "\$@"; do
		if [ -f "\$archive" ] ; then
			case \$archive in
				*.tar.bz2)   tar xvjf \$archive    ;;
				*.tar.gz)    tar xvzf \$archive    ;;
				*.bz2)       bunzip2 \$archive     ;;
				*.rar)       unrar -x \$archive    ;;
				*.gz)        gunzip \$archive      ;;
				*.tar)       tar xvf \$archive     ;;
				*.tbz2)      tar xvjf \$archive    ;;
				*.tgz)       tar xvzf \$archive    ;;
				*.zip)       unzip \$archive       ;;
				*.Z)         uncompress \$archive  ;;
				*.7z)        7z x \$archive        ;;
				*)           echo "don't know how to extract '\$archive'..." ;;
			esac
		else
			echo "'\$archive' is not a valid file!"
		fi
	done
}

# Disk usage support
alias used='du -sh'
alias usedm='du -s --block-size=1M'
alias usedg='du -s --block-size=1G'

# sudo quick shortcuts
alias reboot='sudo /usr/sbin/reboot'
alias su-vi='sudo vi'
alias su-nano='sudo nano'
alias su-rm='sudo rm'
alias su-cp='sudo cp'
alias su-mv='sudo mv'
alias su-md='sudo mkdir -p'
alias dmesg='sudo /usr/bin/dmesg'
alias mount='sudo /usr/bin/mount'
alias umount='sudo /usr/bin/umount'
alias iotop='sudo /usr/sbin/iotop'
alias apt='sudo /usr/bin/apt'
alias powertop='sudo /usr/sbin/powertop'
alias systemctl='sudo /usr/bin/systemctl'

EOF

# Create a new .bash_aliases for root
cat <<EOF >/root/.bash_aliases
ps -p 2 >/dev/null # LXD Container check
if [ \$? -ne 0 -o "\${SUDO_USER}" != "" ] ; then
	. /etc/profile
fi
EOF
#
################################################################################
#
echo "Configuring APT..."

if [ ! -f /etc/apt/apt.conf.d/99disable-translations ] ; then
	echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/99disable-translations
fi

if [ ! -f /etc/apt/apt.conf.d/99force-ipv4 ] ; then
	echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4
fi

if [ ! -f /etc/apt/apt.conf.d/99autoclean-interval ] ; then
	echo 'APT::Periodic::AutocleanInterval "7";' > /etc/apt/apt.conf.d/99autoclean-interval
fi

if [ ! -f /etc/apt/apt.conf.d/99download-update-interval ] ; then
	echo 'APT::Periodic::Download-Upgradeable-Packages "1";' > /etc/apt/apt.conf.d/99download-update-interval
fi

if [ ! -f /etc/apt/apt.conf.d/99unattended-upgrades ] ; then
	cat > /etc/apt/apt.conf.d/99unattended-upgrades << EOF
// Unattended-Upgrade::Origins-Pattern controls which packages are
// upgraded.
//
Unattended-Upgrade::Origins-Pattern {
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
};

// Remove unused automatically installed kernel-related packages
// (kernel images, kernel headers and kernel version locked tools).
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Do automatic removal of newly unused dependencies after the upgrade
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

// Do automatic removal of unused packages after the upgrade
// (equivalent to apt-get autoremove)
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot *WITHOUT CONFIRMATION* if
//  the file /var/run/reboot-required is found after the upgrade
Unattended-Upgrade::Automatic-Reboot "true";

// Automatically reboot even if there are users currently logged in
// when Unattended-Upgrade::Automatic-Reboot is set to true
Unattended-Upgrade::Automatic-Reboot-WithUsers "true";

// If automatic reboot is enabled and needed, reboot at the specific
// time instead of immediately
//  Default: "now"
Unattended-Upgrade::Automatic-Reboot-Time "04:00";

EOF
fi
#
################################################################################
#
# Some server settings from ProxMenux useful for non-Proxmox servers
#
echo "Tuning Server Settings"

echo "- Increasing System limits..."
cat > /etc/sysctl.d/99-maxwatches.conf << EOF
fs.inotify.max_user_watches = 1048576
fs.inotify.max_user_instances = 1048576
fs.inotify.max_queued_events = 1048576
EOF

cat > /etc/security/limits.d/99-limits.conf << EOF
*    soft     nproc          1048576
*    hard     nproc          1048576
*    soft     nofile         1048576
*    hard     nofile         1048576
*    soft     memlock        unlimited
*    hard     memlock        unlimited
root soft     nproc          unlimited
root hard     nproc          unlimited
root soft     nofile         unlimited
root hard     nofile         unlimited
EOF

cat > /etc/sysctl.d/99-maxkeys.conf << EOF
kernel.keys.maxbytes=100000000
kernel.keys.root_maxkeys=1000000
kernel.keys.maxkeys=1000000
EOF

cat > /etc/sysctl.d/99-swap.conf << EOF
vm.swappiness = 10
vm.vfs_cache_pressure = 100
EOF

cat > /etc/sysctl.d/99-fs.conf << EOF
fs.nr_open = 12000000
fs.file-max = 9223372036854775807
fs.aio-max-nr = 1048576
EOF

for file in /etc/systemd/system.conf /etc/systemd/user.conf; do
	if ! grep -q "^DefaultLimitNOFILE=" "$file"; then
		echo "DefaultLimitNOFILE=256000" >> "$file"
	fi
done

for file in /etc/pam.d/common-session /etc/pam.d/runuser-l; do
	if ! grep -q "^session required pam_limits.so" "$file"; then
		echo 'session required pam_limits.so' >> "$file"
	fi
done

if ! grep -q "ulimit -n 256000" /root/.profile; then
	echo "ulimit -n 256000" >> /root/.profile
fi

echo "- Optimizing memory settings..."
cat <<EOF > /etc/sysctl.d/99-memory.conf
# Balanced Memory Optimization
vm.swappiness = 10
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
vm.overcommit_memory = 1
vm.max_map_count = 262144
EOF

echo "- Configuring kernel panic behavior..."
cat <<EOF > /etc/sysctl.d/99-kernelpanic.conf
# Enable restart on kernel panic, kernel oops and hardlockup
kernel.core_pattern = /var/crash/core.%t.%p
kernel.panic = 10
kernel.panic_on_oops = 1
kernel.hardlockup_panic = 1
EOF

echo "- Optimizing network settings..."
cat <<'EOF' > /etc/sysctl.d/99-network.conf
# ==========================================================
# ProxMenux - Network tuning (PVE 9 compatible)
# ==========================================================

# Core buffers & queues
net.core.netdev_max_backlog = 8192
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.somaxconn = 8192

# IPv4 hardening
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.all.log_martians = 0

net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.default.log_martians = 0

# rp_filter:
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2

# ICMP
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# TCP/IP
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_rmem = 8192 87380 16777216
net.ipv4.tcp_wmem = 8192 65536 16777216

# Unix sockets
net.unix.max_dgram_qlen = 4096
EOF

sysctl --system > /dev/null 2>&1
#
################################################################################
#
# Entropy settings from ProxMenux
#
echo "Configuring entropy generation to prevent slowdowns..."

/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::='--force-confdef' install haveged > /dev/null 2>&1

cat <<EOF > /etc/default/haveged
#   -w sets low entropy watermark (in bits)
DAEMON_ARGS="-w 1024"
EOF

systemctl daemon-reload > /dev/null 2>&1
systemctl enable haveged > /dev/null 2>&1
#
################################################################################
#
# Log2RAM. Modified from ProxMenux
#
if [ -f /etc/log2ram.conf ] || [ -d /var/log.hdd ]; then
	echo "Clearing previous Log2RAM install..."

    systemctl stop log2ram log2ram-daily.timer >/dev/null 2>&1 || true
    systemctl disable log2ram log2ram-daily.timer >/dev/null 2>&1 || true

    rm -f /etc/cron.d/log2ram /etc/cron.d/log2ram-auto-sync \
          /etc/cron.hourly/log2ram /etc/cron.daily/log2ram \
          /etc/cron.weekly/log2ram /etc/cron.monthly/log2ram 2>/dev/null || true
    rm -f /usr/local/bin/log2ram-check.sh /usr/local/bin/log2ram /usr/sbin/log2ram 2>/dev/null || true
    rm -f /etc/systemd/system/log2ram.service \
          /etc/systemd/system/log2ram-daily.timer \
          /etc/systemd/system/log2ram-daily.service \
          /etc/systemd/system/sysinit.target.wants/log2ram.service 2>/dev/null || true
    rm -rf /etc/systemd/system/log2ram.service.d 2>/dev/null || true
    rm -f /etc/log2ram.conf* 2>/dev/null || true
    rm -rf /etc/logrotate.d/log2ram /var/log.hdd /tmp/log2ram 2>/dev/null || true

    systemctl daemon-reexec >/dev/null 2>&1 || true
    systemctl daemon-reload >/dev/null 2>&1 || true
    systemctl restart cron >/dev/null 2>&1 || true
fi

RAM_SIZE_GB=$(free -g | awk '/^Mem:/{print $2}')
RAM_SIZE_MB=$(free -m | awk '/^Mem:/{print $2}')
[[ -z "$RAM_SIZE_GB" || "$RAM_SIZE_GB" -eq 0 ]] && RAM_SIZE_GB=2

if (( RAM_SIZE_GB <= 2 )); then
	echo "[WARN] Low RAM detected (${RAM_SIZE_MB}M). Disabling Log2RAM."
	ENABLE_LOG2RAM=FALSE; LOG2RAM_SIZE="128M"
elif (( RAM_SIZE_GB <= 8 )); then
	LOG2RAM_SIZE="256M"; CRON_HOURS=1
elif (( RAM_SIZE_GB <= 16 )); then
	LOG2RAM_SIZE="512M"; CRON_HOURS=2
elif (( RAM_SIZE_GB <= 32 )); then
	LOG2RAM_SIZE="1024M"; CRON_HOURS=4
else
	LOG2RAM_SIZE="2048M"; CRON_HOURS=6
fi

# Check if we're in an LXC/INCUS container
# If we are then DON'T run Log2RAM
grep -qa container=lxc /proc/1/environ
if [ $? -eq 0 ] ; then
	echo "[WARN] Container detected. Disabling Log2RAM."
	ENABLE_LOG2RAM=FALSE
fi

rm -rf /tmp/log2ram 2>/dev/null || true
if [ "$ENABLE_LOG2RAM" == "TRUE" ] ; then
	if git clone https://github.com/azlux/log2ram.git /tmp/log2ram >/dev/null 2>>/tmp/log2ram_install.log; then
		echo "Configuring Log2RAM..."
		cd /tmp/log2ram
		bash install.sh

		systemctl enable --now log2ram >/dev/null 2>&1 || true
		systemctl daemon-reload >/dev/null 2>&1 || true

		echo "- Detected RAM: $RAM_SIZE_GB GB"
		echo "- Log2RAM size set to: $LOG2RAM_SIZE"
		sed -i "s/^SIZE=.*/SIZE=$LOG2RAM_SIZE/" /etc/log2ram.conf

		LOG2RAM_BIN="$(command -v log2ram || echo /usr/sbin/log2ram)"

		cat > /etc/cron.d/log2ram <<EOF
# Log2RAM periodic sync - Created by ProxMenux
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAILTO=""
0 */$CRON_HOURS * * * root $LOG2RAM_BIN write >/dev/null 2>&1
EOF
		chmod 0644 /etc/cron.d/log2ram
		chown root:root /etc/cron.d/log2ram
		echo "Log2RAM write scheduled every $CRON_HOURS hour(s)"

		cat > /usr/local/bin/log2ram-check.sh <<'EOF'
#!/usr/bin/env bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

CONF_FILE="/etc/log2ram.conf"
L2R_BIN="$(command -v log2ram || true)"
[[ -z "$L2R_BIN" && -x /usr/sbin/log2ram ]] && L2R_BIN="/usr/sbin/log2ram"
[[ -z "$L2R_BIN" ]] && exit 0

SIZE_MiB="$(grep -E '^SIZE=' "$CONF_FILE" 2>/dev/null | cut -d'=' -f2 | tr -dc '0-9')"
[[ -z "$SIZE_MiB" ]] && SIZE_MiB=128
LIMIT_BYTES=$(( SIZE_MiB * 1024 * 1024 ))
THRESHOLD_BYTES=$(( LIMIT_BYTES * 90 / 100 ))

USED_BYTES="$(df -B1 --output=used /var/log 2>/dev/null | tail -1 | tr -dc '0-9')"
[[ -z "$USED_BYTES" ]] && exit 0

LOCK="/run/log2ram-check.lock"
exec 9>"$LOCK" 2>/dev/null || exit 0
flock -n 9 || exit 0

if (( USED_BYTES > THRESHOLD_BYTES )); then
  "$L2R_BIN" write 2>/dev/null || true
fi
EOF
		chmod +x /usr/local/bin/log2ram-check.sh

		cat > /etc/cron.d/log2ram-auto-sync <<'EOF'
# Log2RAM auto-sync based on /var/log usage - Created by ProxMenux
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAILTO=""
*/5 * * * * root /usr/local/bin/log2ram-check.sh >/dev/null 2>&1
EOF
		chmod 0644 /etc/cron.d/log2ram-auto-sync
		chown root:root /etc/cron.d/log2ram-auto-sync

		systemctl restart cron >/dev/null 2>&1 || true
		echo "Auto-sync enabled when /var/log exceeds 90% of $LOG2RAM_SIZE"

		if [ ! -d /var/log.hdd ] ; then
			mkdir -p /var/log.hdd
			chown root:root /var/log.hdd
		fi
	fi
fi

echo "Adjusting systemd-journald limits..."
if [[ -f /etc/systemd/journald.conf ]]; then
	cp -n /etc/systemd/journald.conf /etc/systemd/journald.conf.bak.$(date +%Y%m%d-%H%M%S)
fi

SIZE_MB=$(echo "$LOG2RAM_SIZE" | tr -dc '0-9')
USE_MB=$(( SIZE_MB * 55 / 100 ))
KEEP_MB=$(( SIZE_MB * 10 / 100 ))
RUNTIME_MB=$(( SIZE_MB * 25 / 100 ))

[ "$USE_MB" -lt 80 ] && USE_MB=80
[ "$RUNTIME_MB" -lt 32 ] && RUNTIME_MB=32
[ "$KEEP_MB" -lt 8 ] && KEEP_MB=8


sed -i '/^\[Journal\]/,$d' /etc/systemd/journald.conf 2>/dev/null || true
tee -a /etc/systemd/journald.conf >/dev/null <<EOF
[Journal]
Storage=persistent
SplitMode=none
RateLimitIntervalSec=30s
RateLimitBurst=1000
ForwardToSyslog=no
ForwardToWall=no
Seal=no
Compress=yes
SystemMaxUse=${USE_MB}M
SystemKeepFree=${KEEP_MB}M
RuntimeMaxUse=${RUNTIME_MB}M
MaxLevelStore=warning
MaxLevelSyslog=warning
MaxLevelKMsg=warning
MaxLevelConsole=notice
MaxLevelWall=crit
EOF

systemctl restart systemd-journald >/dev/null 2>&1 || true
echo "Journald configuration adjusted to ${USE_MB}M (Log2RAM ${LOG2RAM_SIZE})"
#
################################################################################
#
# Optimize logrotate
#
if ! grep -q "# RAM optimized configuration" "/etc/logrotate.conf"; then
	echo "Optimizing logrotate configuration..."
	cp -f "/etc/logrotate.conf" "/etc/logrotate.conf.bak" 2>/dev/null
	cat <<EOF > "/etc/logrotate.conf"
# RAM optimized configuration (Log2RAM-friendly)
daily
su root adm
rotate 7
size=10M
compress
delaycompress
missingok
notifempty
create 0640 root adm
copytruncate
include /etc/logrotate.d
EOF
	systemctl restart logrotate > /dev/null 2>&1
fi
#
################################################################################################################################################################
#
if [ ! -f /var/lib/plocate/plocate.db ] ; then
	echo "Updating plocate.db"
	updatedb
fi
#
################################################################################################################################################################
#
if [ ! -f /root/.hushlogin ] ; then
	echo "Setting root .hushlogin"
	touch /root/.hushlogin
fi
if [ ! -f /etc/skel/.hushlogin ] ; then
	echo "Setting default .hushlogin"
	touch /etc/skel/.hushlogin
fi
#
################################################################################################################################################################
#
echo "Installing 'spectre-meltdown-checker' to /usr/bin"
if [ ! -d /usr/share/spectre-meltdown-checker ] ; then
    git clone https://github.com/speed47/spectre-meltdown-checker /usr/share/spectre-meltdown-checker >/dev/null
else
    cd /usr/share/spectre-meltdown-checker
    git pull  >/dev/null
fi
chmod a+x /usr/share/spectre-meltdown-checker/spectre-meltdown-checker.sh
[ -f /usr/local/bin/spectre-meltdown-checker ] && rm /usr/local/bin/spectre-meltdown-checker
[ -f /usr/bin/spectre-meltdown-checker ]       && rm /usr/bin/spectre-meltdown-checker
ln -s /usr/share/spectre-meltdown-checker/spectre-meltdown-checker.sh /usr/bin/spectre-meltdown-checker
#
################################################################################################################################################################
#
echo "Install date: `date`" > /etc/pve/.setup
#
################################################################################################################################################################
#
get_proxmox_version
read -r -p "Reboot ${PROXMOX_VERSION} now? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]; then
    echo "Rebooting ${PROXMOX_VERSION}"
    reboot
fi
#
################################################################################################################################################################
